### ISSUE TITLE
Test uploading a sheet and downloading a KMP

### ISSUE THREAD

**Issue by jienius** [eddieantonio/predictive-text-studio#32] opened 2020-09-19 16:16 UTC

**Comment by eddieantonio** [comment] 2020-09-19 22:56
**Blocked by** #40

**Comment by eddieantonio** [comment] 2020-10-14 22:10
This _might_ be a duplicate of #27.

**Comment by eddieantonio** [comment] 2020-10-15 20:28
Fixed by #110

**Closed as completed by eddieantonio** 2020-10-15 20:28 UTC
Labels: duplicate, enhancement, UI, 🔥 High priority, cypress-testing
